# Introduction to Scikit-Learn(sklearn)

This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover:

0. An end-to-end Scikit-Learn workflow
1. Gettting the data ready
2. Choose the right estimator/algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and Load a trained model
7. Putting it all together

## 0. An end-to-end Scikit-learn workflow

In [1]:
# 1. Get the data ready

import pandas as pd
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [13]:
import numpy as np

In [3]:
# Separate the feature matrix and target matrix

X = heart_disease.drop("target", axis=1) # feature variables
Y = heart_disease["target"] # target variable or labels

In [5]:
# 2. Choose the right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier

# Random Forest Classifier is the machine learning model for classification since we're doing a classfication problem

In [8]:
clf = RandomForestClassifier()

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [11]:
# 3. Fit the model/algorithm to the training data

# first, split the data into training and test set
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

In [12]:
clf.fit(X_train, Y_train)

RandomForestClassifier()

In [15]:
# make predictions
Y_label = clf.predict(np.array([1,2,3,4]))

/Users/starlord/Desktop/Work/Learn/DataScience/ml-ds-tools-library-introduction/env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [16]:
# throwing error above because, our model only learnt what we have taught to understand 2-D arrays 
# and it trained with X_train/X_test shape

y_preds = clf.predict(X_test)
y_preds

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1])

In [17]:
# and note that the above output looks like something Y_test
Y_test

30     1
144    1
48     1
279    0
148    1
      ..
238    0
5      1
82     1
288    0
278    0
Name: target, Length: 61, dtype: int64

In [18]:
# 4. Evaluate the model on training data and test data
clf.score(X_train,Y_train) # .score gives the mean accuracy of the model

1.0

In [19]:
clf.score(X_test,Y_test)

0.7704918032786885

In [20]:
# other metrics

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [24]:
print(classification_report(Y_test, y_preds))

              precision    recall  f1-score   support

           0       0.79      0.74      0.77        31
           1       0.75      0.80      0.77        30

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61



In [25]:
confusion_matrix(Y_test, y_preds)

array([[23,  8],
       [ 6, 24]])

In [26]:
accuracy_score(Y_test, y_preds)

0.7704918032786885

In [30]:
# 5. Improve a model

# Try different amount of n_estimators (one of the estimators)

np.random.seed(42) # so everytime take same numbers of seed(40)

for i in range(10,100,10):
    print(f"Trying the model with n_estimators = {i}")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, Y_train)
    print(f"Accuracy :{clf.score(X_test,Y_test) * 100:.2f}%")    

Trying the model with n_estimators = 10
Accuracy :83.61%
Trying the model with n_estimators = 20
Accuracy :73.77%
Trying the model with n_estimators = 30
Accuracy :80.33%
Trying the model with n_estimators = 40
Accuracy :77.05%
Trying the model with n_estimators = 50
Accuracy :81.97%
Trying the model with n_estimators = 60
Accuracy :75.41%
Trying the model with n_estimators = 70
Accuracy :81.97%
Trying the model with n_estimators = 80
Accuracy :80.33%
Trying the model with n_estimators = 90
Accuracy :78.69%


In [32]:
# 6. Save a model and load it

import pickle # python library to read and write

pickle.dump(clf, open("random_forest_model_1.pkl", "wb")) # wb : write binary



In [33]:
# load model

loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb")) # rb: read binaries
loaded_model.score(X_test, Y_test)

0.7868852459016393

## 1. Getting our data ready to be used with Machine Learning

Three main things we have to do:
   1. Split the data into features and target(labels), usually 'X' and 'y'
   2. Filling(also called imputing) or disregarding missing values
   3. Converting non-numerical values to numerical values (also called feature encoding), as machine understands only 0 and 1.

In [1]:
# first we need to import the standard libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [35]:
# import the data or create the data
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [36]:
# 1. Splitting data into feature variable and target Variable from data imported

X = heart_disease.drop("target", axis = 1)
y = heart_disease["target"]



In [37]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [38]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [39]:
# Split the data into training and test sets
# according to Machine Learning workflow, we must separate the data for training and evaluation
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [40]:
X.shape, y.shape, X_train.shape, X_test.shape, y_train.shape, y_test.shape

((303, 13), (303,), (242, 13), (61, 13), (242,), (61,))

### 1.1 Make sure all the data is numerical

In [3]:
car_sales = pd.read_csv("car-sales-extended.csv")
car_sales

# Problem we are solving here, to predict Price on the basis of given Make, Colour, Odometer, Doors

# This is a regression problem of prediction

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [4]:
# Split the data into X and y

X = car_sales.drop("Price", axis = 1)
y = car_sales["Price"]

In [5]:
# Split into Train and Test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
# Build Machine learning model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'BMW'

### So here we can see that machine can't understand strings, so we have to convert string data into numerical

In [7]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [9]:
# Turn the categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot = OneHotEncoder()
categorical_feature = ['Make','Colour','Doors']

# Here Doors are also a categorical feature, since some cars have 4 doors, some have 5 and some have 3

transformer = ColumnTransformer([('one_hot', one_hot, categorical_feature)], remainder='passthrough')

transformed_X = transformer.fit_transform(X)


In [10]:
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [11]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [14]:
# Let's refit the model

np.random.seed(42)

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model.fit(X_train, y_train)

model.score(X_test, y_test)

0.3235867221569877

In [16]:
import sklearn
print(sklearn.__version__)

1.1.1
